### PR TITLE
Fix floating buttons covering content in DEX-view on mobile

### LINKED ISSUE #546: DEX on mobile: Floating bottom buttons cover some content
Reason: We add a placeholder `<div>` of the same height as the bottom buttons to the content on mobile, but the two-column layout leads to the placeholder being placed at the end of the left column = in the center.

### PR DESCRIPTION
**Pull request by Marcel-Ebert**
- [x] Render the `<DialogActions>` below the `<Explanation>` in DEX dialog on mobile / small screens

Closes #546.

### CODE REVIEW

File: src/components/TradeAsset/TradingForm.tsx [hunk 1]
```diff
@@ -76,12 +77,14 @@ function TradingForm(props: Props) {
             </Box>
           ) : null}
           <div style={{ flexGrow: 1 }} />
-          <DialogActions
-            amount={amount}
-            disabled={amountString === "" || isDisabled(amount, price, Number.parseFloat(props.sellingBalance))}
-            price={price}
-            style={{ justifySelf: "flex-end" }}
-          />
+          {isSmallScreen ? null : (
```
Comment (andywer) [inline src/components/TradeAsset/TradingForm.tsx]: One detail I'd like to have fixed before merging this:

Let's deduplicate by putting the `<DialogActions ... />` in a variable we use in both places.
